Update store-and-forward-module.mdx
meshtastic/meshtastic pull request #1174
Opened 2024-04-04 16:18 UTC by TBoons

Docs were outdated with S&F configuration not being available on the webclient.  Minor update.

2024-04-04 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/meshtastic?pullRequest=1174) it.</sub>

2024-04-10 04:23 UTC, pdxlocations requested changes
For consistency, could you change this to what the other module config pages use: "All Store & Forward module config options are available in the Web UI."

Some day I'd like to make all of these worded the same for all clients...

2024-04-10 14:52 UTC, pdxlocations approved these changes

2024-04-10 15:54 UTC, merged

2024-04-10 16:49 UTC, TBoons commented
Hey Thanks! I will try and see what else I can work on. This project is awesome.

2024-04-10 16:53 UTC, pdxlocations commented
> Hey Thanks! I will try and see what else I can work on. This project is awesome.

Its the community (like you) that make it so!