local-groups.mdx
meshtastic/meshtastic pull request #1218
Opened 2024-04-25 15:49 UTC by rtaylo

Added Nashville, TN

2024-04-25 15:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/meshtastic?pullRequest=1218) it.</sub>

2024-04-26 23:34 UTC, pdxlocations requested changes
Hello, thanks for your contribution.  Could you please rearrange this to keep it alphabetical by state?

Also we'll require you sign the CLA before merge.  Thanks!

2024-04-27 01:22 UTC, rtaylo commented
> Hello, thanks for your contribution. Could you please rearrange this to keep it alphabetical by state?
> 
> Also we'll require you sign the CLA before merge. Thanks!

Not really sure how to use Github, but I made another pull request with that change. 
(local-groups.mdx #1225)

2024-04-27 05:47 UTC, pdxlocations commented
closed in favor of #1225

2024-04-27 05:47 UTC, closed without merging