Update radio-settings.mdx
meshtastic/meshtastic pull request #1278
Opened 2024-05-30 20:04 UTC by jwcrawley

Include the default frequencies for the associated presets set within the app.

2024-05-30 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1278) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1278) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/meshtastic?pullRequest=1278) it.</sub>

2024-05-30 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1278) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1278) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/meshtastic?pullRequest=1278) it.</sub>

2024-06-01 13:57 UTC, tekstrand requested changes
Wouldn't these only be accurate for the US? That's what the calculator up above on the page is for https://meshtastic.org/docs/overview/radio-settings/#frequency-slot-calculator

If we'd like to display them all without having to use the calculator, I'd suggest we create a table with all regions or a table for each region, rather than adding it to this table

2024-06-02 06:13 UTC, pdxlocations commented
@tekstrand is correct, this PR would only apply to the US region setting and could be misleading.
There is a default LongFast frequency slot list here: https://meshtastic.org/docs/configuration/tips/#default-primary-frequency-slots-by-region
A frequency rage table here:
https://meshtastic.org/docs/configuration/radio/lora/

For preset frequencies by country the calculator should be used.

2024-06-02 06:13 UTC, closed without merging