Update harbor-breeze-solar-enclosure.mdx
meshtastic/meshtastic pull request #1610
Opened 2024-11-30 12:01 UTC by thatSFguy

## What did you change
Fixed the broken link to the Amazon antenna page.  Added note about the worse performance when not keeping those types of antennas straight.  Added two links for 3d printed mounting options related to this project.

## Why did you change it
- Link was broken
- After a fellow Mesher pointed out that he had tested many of these 3dB antenna's at 90deg configuration, I performed the same test on 5-6 antennas and found that they go from sub 1.5 SWR to well over 2.5 SWR and higher in a 90deg configuration.
- Added two alternate mounting option links for 3D printed items related to this project.

## Screenshots
### Before

### After

2024-11-30 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=1610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/meshtastic?pullRequest=1610) it.</sub>

2024-11-30 18:41 UTC, pdxlocations requested changes
Just some minor changes please.

2024-11-30 18:47 UTC, pdxlocations commented
@tavdog any objections/corrections?

2024-11-30 19:17 UTC, tavdog commented
> @tavdog any objections/corrections?

Fine by me ;)

2024-12-03 03:07 UTC, pdxlocations approved these changes

2024-12-03 14:23 UTC, merged