`set region` for firmware v1.3 has added
meshtastic/Meshtastic pull request #403
Opened 2022-09-11 14:55 UTC by osmanovv

2022-09-11 15:08 UTC, garthvh requested changes
Please remove the 1.2 section, all 1.2 docs are under the 1.2 EOL menu item and will be deleted shortly.

2022-09-12 06:46 UTC, caveman99 commented
Watch out! The names for some regions have changed with the latest proto changes. E.G. EU433 is EU_433 now.

2022-09-12 19:12 UTC, garthvh approved these changes

2022-09-12 19:12 UTC, garthvh approved these changes

2022-09-12 19:15 UTC, merged