param value is case sensitive
meshtastic/Meshtastic pull request #405
Opened 2022-09-11 15:02 UTC by osmanovv

Using Python CLI v1.3.29:
```
>meshtastic --set lora.modem_preset longSlow
Connected to radio
lora.modem_preset does not have an enum called longSlow, so you can not set it.
Choices in sorted order are:
    LongFast
    LongSlow
    MedFast
    MedSlow
    ShortFast
    ShortSlow
    VLongSlow
LocalConfig and LocalModuleConfig do not have attribute lora.modem_preset.
```

2022-09-11 15:05 UTC, garthvh requested changes
These have been updated in the latest protobufs a bit, VeryLongSlow, MediumSlow, MediumFast

2022-09-12 17:48 UTC, osmanovv commented
> These have been updated in the latest protobufs a bit, VeryLongSlow, MediumSlow, MediumFast

🤦‍♂️ They have been updated again to `LONG_FAST`, `LONG_SLOW`, `VERY_LONG_SLOW`, etc

https://github.com/meshtastic/Meshtastic-protobufs/blob/master/config.proto

2022-09-12 18:31 UTC, garthvh approved these changes

2022-09-12 18:32 UTC, garthvh approved these changes

2022-09-12 19:07 UTC, merged