Updated set-canned-messages.
meshtastic/Meshtastic pull request #436
Opened 2022-10-11 23:42 UTC by matyaskrizek

Removing last pipe from meshtastic --set-canned-message "I need an alpinist!|Call Me|Roger Roger|Keep Calm|On my way|".

2022-10-11 23:52 UTC, thebentern requested changes

2022-10-11 23:52 UTC, thebentern commented on docs/settings/moduleconfig/canned-message.mdx
> +meshtastic --set-canned-message "I need an alpinist!|Call Me|Roger Roger|Keep Calm|"
There's still a trailing pipe

2022-10-12 00:04 UTC, matyaskrizek commented on docs/settings/moduleconfig/canned-message.mdx
> +meshtastic --set-canned-message "I need an alpinist!|Call Me|Roger Roger|Keep Calm|"
I misunderstood what was desired, new commit removes trailing pipe.

2022-10-12 00:11 UTC, garthvh approved these changes

2022-10-12 00:11 UTC, merged