Update installation.mdx
meshtastic/meshtastic pull request #494
Opened 2022-11-03 11:49 UTC by Dtrieb

Add WLAN Label.

2022-11-03 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/meshtastic?pullRequest=494) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/meshtastic?pullRequest=494) it.</sub>

2022-11-03 12:16 UTC, caveman99 requested changes
That doesn't seem to fit thematically. I'd rather remove that obscure WLAN Comment.

2022-11-03 12:24 UTC, garthvh commented
> 

Same

2022-11-05 02:22 UTC, sachaw commented
Not sure why this was added without any content.

2022-11-05 02:22 UTC, closed without merging