nRF52 OTA documentation
meshtastic/meshtastic pull request #710
Opened 2023-07-06 06:34 UTC by pdxlocations

This PR adds the OTA firmware update methods for nRF52 devices.
[preview link](https://sandbox-git-ota-update-pdxlocations.vercel.app/docs/getting-started/flashing-firmware/nrf52/)

2023-07-06 06:52 UTC, garthvh commented
Can apple be the selected tab since it actually works?

2023-07-06 07:00 UTC, pdxlocations commented
> Can apple be the selected tab since it actually works?

@garthvh Yes that's smart.  (I use my wife's iPhone to update my nRF's!)

2023-07-06 14:01 UTC, charminULTRA commented
Android tab: "nRF DFU app (v2.3.0)" - Can you specify this is the **Android** nRF DFU app?

What's the difference between the Android DFU App and the Android Connect app?

2023-07-07 14:19 UTC, charminULTRA requested changes

2023-07-07 15:09 UTC, pdxlocations commented on docs/getting-started/flashing-firmware/nrf52/ota.mdx
The DFU App is MUCH simpler to use and the current release works on Apple.  The only app that works on Android (for now) is an old version of the Connect app which has to be manually installed from GitHub.  Maybe that could be a little clearer here.

2023-07-07 15:19 UTC, pdxlocations commented
@charminULTRA I gave it a shot.

2023-07-08 21:42 UTC, garthvh approved these changes

2023-07-11 21:23 UTC, charminULTRA commented on docs/getting-started/flashing-firmware/nrf52/ota.mdx
> +OTA firmware updates are available for Android using and older release of the more advanced nRF Connect App __version 4.24.3__ which is available for download from the [Nordic Semiconductor GitHub pa
Small typo, says "using and older"

2023-07-11 21:24 UTC, charminULTRA requested changes
There's a small typo, I left a comment for the location

2023-07-11 23:24 UTC, pdxlocations commented
@charminULTRA good catch! fixed.

2023-07-12 01:53 UTC, charminULTRA approved these changes

2023-07-12 01:53 UTC, merged