Update Techo page to include flashing information
meshtastic/Meshtastic pull request #81
Opened 2021-11-07 14:38 UTC by KrazyKerbalnaut

2021-11-07 20:54 UTC, sachaw commented
Please rebase and I'll merge.

2021-11-09 20:43 UTC, sachaw requested changes

2021-11-09 20:43 UTC, sachaw commented on website/docusaurus.config.js
> +      id: 'support_us',
Please change to something relevant "play_store_workaround" for example or omit it to use default

2021-11-09 20:43 UTC, sachaw commented on website/docusaurus.config.js
> +      isCloseable: false,
Should be true

2021-11-09 20:43 UTC, sachaw commented on website/docusaurus.config.js
> +        'Android app unavailable in the Google Play Store store. Please check out installing manually by side-loading or using the Amazon Apps method  <a href="/docs/software/android/android-installa
I'd change the "Please check out installing manually..." Bit to "Please install from GitHub or Amazon Store. And have the text be the link.

2021-11-09 22:01 UTC, KrazyKerbalnaut commented
I see that you requested changes, but I'm not able to see any of the other requests other than the 3 that you pointed out. Check those out and get back to me

2021-11-09 22:31 UTC, sachaw requested changes
Last change!

2021-11-09 22:31 UTC, sachaw commented on website/docusaurus.config.js
> +        '<a href="/docs/software/android/android-installation" href="#">Android app unavailable in the Google Play Store store. Install by side-loading from git-hub or from Amazon Apps.</a>',
I'd change it to be: 
```
Android app unavailable in the Google Play Store store. Install by side-loading from <a href="https://github.com/meshtastic/Meshtastic-Android/releases">GitHub</a> or from <a href="https://www.amazon.com/Geeksville-Industries-Meshtastic/dp/B08CY9394Q">Amazon</a>.
```

Just makes it a little more concise.

2021-11-09 22:55 UTC, merged