Add rak enclosure harbor breeze solar hack how-to
meshtastic/meshtastic pull request #928
Opened 2024-01-19 05:54 UTC by tavdog

Add a link to the RAK enclosures page and also add a HOW-TO page under RAK dir.

2024-01-21 06:25 UTC, pdxlocations requested changes
Awesome project!  Could you move the build into a sub-page of enclosures per @rcarteraz and @tropho23 's request on discord?

2024-01-21 06:26 UTC, pdxlocations commented
Your preview Vercel link from Discord helps with tracking the changes:
https://meshtastic-docs-sigma.vercel.app/docs/hardware/devices/rak/harbor_breeze_solar

2024-01-21 08:51 UTC, tavdog commented
> Awesome project! Could you move the build into a sub-page of enclosures per @rcarteraz and @tropho23 's request on discord?

I would but I don't know how to create a sub folder with this markup.

2024-01-21 18:12 UTC, pdxlocations commented
> > Awesome project! Could you move the build into a sub-page of enclosures per @rcarteraz and @tropho23 's request on discord?
> 
> I would but I don't know how to create a sub folder with this markup.

- You'll want to create a new folder /docs/hardware/devices/rak/enclosures
- move enclosures.mdx into the new folder
- rename enclosures.mdx to index.mdx
- move harbor_breeze_solar_enclosure.mdx into the new folder
- change your sidebar_position to 1

2024-01-21 18:14 UTC, pdxlocations commented
One other thing, are you able to reduce the file sizes of your images?  They load really slow.  

<img width="819" alt="Screenshot 2024-01-21 at 10 05 04 AM" src="https://github.com/meshtastic/meshtastic/assets/117498748/784f164a-8de2-4a1c-ab9f-d36d99c45b5f">

2024-01-21 18:17 UTC, pdxlocations commented on docs/hardware/devices/rak/enclosures.mdx
> +![Harbor Breeze Solar LED Meshtastci Hack Complete](/img/enclosures/hbmh_complete.png)
typo here "Meshtastci"

2024-01-21 23:15 UTC, tavdog commented
> > > Awesome project! Could you move the build into a sub-page of enclosures per @rcarteraz and @tropho23 's request on discord?
> > 
> > 
> > I would but I don't know how to create a sub folder with this markup.
> 
> * You'll want to create a new folder /docs/hardware/devices/rak/enclosures
> * move enclosures.mdx into the new folder
> * rename enclosures.mdx to index.mdx
> * move harbor_breeze_solar_enclosure.mdx into the new folder
> * change your sidebar_position to 1

Ok. i'll give a try and reduce image size.
and fix mastastcli ( just alt image text though )

2024-01-22 03:43 UTC, pdxlocations approved these changes

2024-01-22 03:43 UTC, merged